-- Anonymous pageview tracking table
-- Run this in Supabase SQL editor.

create table if not exists public.acfh_page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page text not null,
  source text not null default 'web',
  client_id text,
  client_platform text,
  client_browser text
);

alter table public.acfh_page_views
  add column if not exists client_id text;

alter table public.acfh_page_views
  add column if not exists client_platform text;

alter table public.acfh_page_views
  add column if not exists client_browser text;

create index if not exists acfh_page_views_page_created_at_idx
  on public.acfh_page_views (page, created_at desc);

create index if not exists acfh_page_views_created_at_idx
  on public.acfh_page_views (created_at desc);

create index if not exists acfh_page_views_source_created_at_idx
  on public.acfh_page_views (source, created_at desc);

-- Daily aggregation view: access count + unique clients (anonymous).
create or replace view public.acfh_page_views_daily as
select
  (created_at at time zone 'utc')::date as day,
  page,
  source,
  coalesce(nullif(client_platform, ''), 'Unknown') as client_platform,
  coalesce(nullif(client_browser, ''), 'Unknown') as client_browser,
  count(*)::bigint as accesses,
  count(distinct client_id)::bigint as unique_clients
from public.acfh_page_views
group by 1,2,3,4,5
order by day desc, page asc, source asc;

-- Simple daily summary without client breakdown.
create or replace view public.acfh_page_views_daily_summary as
select
  (created_at at time zone 'utc')::date as day,
  page,
  source,
  count(*)::bigint as accesses,
  count(distinct client_id)::bigint as unique_clients
from public.acfh_page_views
group by 1,2,3
order by day desc, page asc, source asc;
